# Generated by Django 2.0.7 on 2018-07-15 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='对接人姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='对接人电话')),
                ('service', models.CharField(max_length=10, verbose_name='服务内容')),
                ('waiting_time', models.CharField(max_length=6, verbose_name='等待对接时长')),
                ('overall_satisfaction', models.CharField(max_length=6, verbose_name='现场及调度满意度')),
                ('attitude', models.CharField(max_length=6, verbose_name='人员态度满意度')),
                ('cycle', models.CharField(max_length=6, verbose_name='作业周期')),
                ('eat', models.CharField(max_length=2, verbose_name='是否用餐或发放餐券')),
                ('proposal', models.CharField(max_length=500, verbose_name='建议')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '数据表',
                'verbose_name_plural': '数据表',
            },
        ),
    ]
